import rawCities from "./data/us-cities.json";

export type City = {
  id: string;
  name: string;
  state: string;
  stateCode: string;
  population: number;
  tier: Tier;
  /** Local phone area code(s), e.g. "813" or "310 / 323". */
  areaCode: string;
};

const STATES: Record<string, string> = {
  AL: "Alabama", AK: "Alaska", AZ: "Arizona", AR: "Arkansas", CA: "California",
  CO: "Colorado", CT: "Connecticut", DE: "Delaware", DC: "District of Columbia",
  FL: "Florida", GA: "Georgia", HI: "Hawaii", ID: "Idaho", IL: "Illinois",
  IN: "Indiana", IA: "Iowa", KS: "Kansas", KY: "Kentucky", LA: "Louisiana",
  ME: "Maine", MD: "Maryland", MA: "Massachusetts", MI: "Michigan", MN: "Minnesota",
  MS: "Mississippi", MO: "Missouri", MT: "Montana", NE: "Nebraska", NV: "Nevada",
  NH: "New Hampshire", NJ: "New Jersey", NM: "New Mexico", NY: "New York",
  NC: "North Carolina", ND: "North Dakota", OH: "Ohio", OK: "Oklahoma", OR: "Oregon",
  PA: "Pennsylvania", RI: "Rhode Island", SC: "South Carolina", SD: "South Dakota",
  TN: "Tennessee", TX: "Texas", UT: "Utah", VT: "Vermont", VA: "Virginia",
  WA: "Washington", WV: "West Virginia", WI: "Wisconsin", WY: "Wyoming",
};

export type Tier = "Major" | "Mid" | "Small";

/** Market size used to group cities in the picker and report. */
export function tierFor(population: number): Tier {
  if (population >= 250_000) return "Major";
  if (population >= 50_000) return "Mid";
  return "Small";
}

// ~4,300 US local-service markets (10k+ population, plus each state's 10 largest places).
// Generated by scripts/build-cities.mjs from GeoNames.
const RAW = rawCities as [string, string, number, string][];

export const CITIES: City[] = RAW.map(([name, stateCode, population, areaCode]) => ({
  id: `${name}-${stateCode}`.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
  name,
  state: STATES[stateCode],
  stateCode,
  population,
  tier: tierFor(population),
  areaCode,
})).sort((a, b) => b.population - a.population);

const BY_ID = new Map(CITIES.map((c) => [c.id, c]));
const BY_NAME = new Map(CITIES.map((c) => [`${c.name}|${c.stateCode}`, c]));

export const STATE_CODES = [...new Set(CITIES.map((c) => c.stateCode))].sort();

/** Location string accepted by DataForSEO's `location_name` parameter. */
export function dataForSeoLocationName(city: City): string {
  return `${city.name},${city.state},United States`;
}

export function findCity(id: string): City | undefined {
  return BY_ID.get(id);
}

/** Area code(s) for a city; works for rows saved before area codes existed. */
export function areaCodeFor(city: string, stateCode: string): string {
  return BY_NAME.get(`${city}|${stateCode}`)?.areaCode ?? "";
}
